typography_spectrum: 0.9336917
color:
  saturation: 0.7433671
  lightness: 0.6202384
  brandStrength: 1
  brandColors:
    - '#F4F4F4'
    - '#1E1B14'
    - '#5C5D57'
    - '#CCB89F'
    - '#7B9FE9'
  rhythmicContrast: 0.001267826
layout_spectrum: 0.4641577
name: Aidenjames
title: Outdoorsman
